# Generated by Django 5.0.6 on 2024-07-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0002_reserva_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='Confirmado', max_length=10),
        ),
    ]
