# Generated by Django 5.0.6 on 2024-07-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0003_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSucursal', models.CharField(max_length=100)),
                ('direccionSucursal', models.CharField(max_length=100)),
                ('telSucursal', models.CharField(max_length=100)),
                ('horariosSucursal', models.CharField(max_length=100)),
            ],
        ),
    ]
